"""initial schema

Revision ID: b6ef44cbf3c0
Revises: 
Create Date: 2026-01-30 11:13:19.257159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ef44cbf3c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mrn', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('insurance_provider', sa.String(), nullable=True),
    sa.Column('policy_number', sa.String(), nullable=True),
    sa.Column('emergency_contact_name', sa.String(), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_mrn'), ['mrn'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('admissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('admission_date', sa.DateTime(), nullable=True),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ward', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_admissions_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admissions'))
    )
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admissions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admissions_patient_id'), ['patient_id'], unique=False)

    op.create_table('allergies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('allergen', sa.String(), nullable=False),
    sa.Column('reaction', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_allergies_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allergies'))
    )
    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allergies_id'), ['id'], unique=False)

    op.create_table('billing_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_billing_items_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_items'))
    )
    with op.batch_alter_table('billing_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_items_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_items_status'), ['status'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_documents_patient_id_patients')),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], name=op.f('fk_documents_uploader_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)

    op.create_table('medical_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('condition_name', sa.String(), nullable=False),
    sa.Column('diagnosis_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_medical_history_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_history'))
    )
    with op.batch_alter_table('medical_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_history_id'), ['id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_tasks_assigned_to_id_users')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_tasks_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    op.create_table('clinical_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('admission_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('structured_content', sa.Text(), nullable=True),
    sa.Column('note_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], name=op.f('fk_clinical_notes_admission_id_admissions')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_clinical_notes_patient_id_patients')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_clinical_notes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_notes'))
    )
    with op.batch_alter_table('clinical_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clinical_notes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_notes_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_clinical_notes_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_notes_note_type'), ['note_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_notes_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_notes_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_clinical_notes_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['clinical_notes.id'], name=op.f('fk_audit_logs_note_id_clinical_notes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_note_id'), ['note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('prescribed_by_id', sa.Integer(), nullable=True),
    sa.Column('source_note_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dosage', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_medications_patient_id_patients')),
    sa.ForeignKeyConstraint(['prescribed_by_id'], ['users.id'], name=op.f('fk_medications_prescribed_by_id_users')),
    sa.ForeignKeyConstraint(['source_note_id'], ['clinical_notes.id'], name=op.f('fk_medications_source_note_id_clinical_notes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medications'))
    )
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medications_id'), ['id'], unique=False)

    op.create_table('note_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('structured_content', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_note_versions_created_by_users')),
    sa.ForeignKeyConstraint(['note_id'], ['clinical_notes.id'], name=op.f('fk_note_versions_note_id_clinical_notes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note_versions'))
    )
    with op.batch_alter_table('note_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_versions_note_id'), ['note_id'], unique=False)

    op.create_table('procedures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('performer_id', sa.Integer(), nullable=True),
    sa.Column('admission_id', sa.Integer(), nullable=True),
    sa.Column('source_note_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], name=op.f('fk_procedures_admission_id_admissions')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_procedures_patient_id_patients')),
    sa.ForeignKeyConstraint(['performer_id'], ['users.id'], name=op.f('fk_procedures_performer_id_users')),
    sa.ForeignKeyConstraint(['source_note_id'], ['clinical_notes.id'], name=op.f('fk_procedures_source_note_id_clinical_notes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procedures'))
    )
    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procedures_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procedures_id'))

    op.drop_table('procedures')
    with op.batch_alter_table('note_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_versions_note_id'))
        batch_op.drop_index(batch_op.f('ix_note_versions_id'))

    op.drop_table('note_versions')
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medications_id'))

    op.drop_table('medications')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_note_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('clinical_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_notes_title'))
        batch_op.drop_index(batch_op.f('ix_clinical_notes_patient_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_notes_note_type'))
        batch_op.drop_index(batch_op.f('ix_clinical_notes_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_clinical_notes_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_clinical_notes_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_notes_created_at'))

    op.drop_table('clinical_notes')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_due_date'))

    op.drop_table('tasks')
    with op.batch_alter_table('medical_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_history_id'))

    op.drop_table('medical_history')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_id'))

    op.drop_table('documents')
    with op.batch_alter_table('billing_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_items_status'))
        batch_op.drop_index(batch_op.f('ix_billing_items_id'))
        batch_op.drop_index(batch_op.f('ix_billing_items_code'))

    op.drop_table('billing_items')
    with op.batch_alter_table('allergies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allergies_id'))

    op.drop_table('allergies')
    with op.batch_alter_table('admissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admissions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_admissions_id'))

    op.drop_table('admissions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_status'))
        batch_op.drop_index(batch_op.f('ix_patients_name'))
        batch_op.drop_index(batch_op.f('ix_patients_mrn'))
        batch_op.drop_index(batch_op.f('ix_patients_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_patients_id'))

    op.drop_table('patients')
    # ### end Alembic commands ###
