"""Add deterioration alerts table

Revision ID: 01f62b44e166
Revises: 73379ff6283a
Create Date: 2026-03-25 17:54:03.498837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f62b44e166'
down_revision: Union[str, Sequence[str], None] = '73379ff6283a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deterioration_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['clinical_notes.id'], name=op.f('fk_deterioration_alerts_note_id_clinical_notes')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_deterioration_alerts_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deterioration_alerts'))
    )
    op.create_index(op.f('ix_deterioration_alerts_id'), 'deterioration_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_deterioration_alerts_patient_id'), 'deterioration_alerts', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deterioration_alerts_patient_id'), table_name='deterioration_alerts')
    op.drop_index(op.f('ix_deterioration_alerts_id'), table_name='deterioration_alerts')
    op.drop_table('deterioration_alerts')
    # ### end Alembic commands ###
