"""Add ClinicalAIInsight and DifferentialDiagnosis tables

Revision ID: 022f91de23d4
Revises: c389b13b129c
Create Date: 2026-02-13 10:33:28.439383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '022f91de23d4'
down_revision: Union[str, Sequence[str], None] = 'c389b13b129c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('differential_diagnoses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('output_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_differential_diagnoses_patient_id_patients')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_differential_diagnoses_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_differential_diagnoses'))
    )
    op.create_index(op.f('ix_differential_diagnoses_id'), 'differential_diagnoses', ['id'], unique=False)
    op.create_table('clinical_ai_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.String(), nullable=True),
    sa.Column('red_flags', sa.Text(), nullable=True),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.Column('missing_info', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['clinical_notes.id'], name=op.f('fk_clinical_ai_insights_note_id_clinical_notes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_ai_insights'))
    )
    op.create_index(op.f('ix_clinical_ai_insights_id'), 'clinical_ai_insights', ['id'], unique=False)
    op.create_index(op.f('ix_clinical_ai_insights_note_id'), 'clinical_ai_insights', ['note_id'], unique=False)
    op.drop_column('patients', 'cached_summary')
    op.drop_column('patients', 'summary_updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('summary_updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('patients', sa.Column('cached_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_clinical_ai_insights_note_id'), table_name='clinical_ai_insights')
    op.drop_index(op.f('ix_clinical_ai_insights_id'), table_name='clinical_ai_insights')
    op.drop_table('clinical_ai_insights')
    op.drop_index(op.f('ix_differential_diagnoses_id'), table_name='differential_diagnoses')
    op.drop_table('differential_diagnoses')
    # ### end Alembic commands ###
