"""Add patient communication and risk models

Revision ID: 0c4b24e55b7f
Revises: 363e4986c015
Create Date: 2026-02-16 10:06:22.903562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c4b24e55b7f'
down_revision: Union[str, Sequence[str], None] = '363e4986c015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readmission_risks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('contributing_factors', sa.Text(), nullable=True),
    sa.Column('prevention_recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_readmission_risks_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_readmission_risks'))
    )
    op.create_index(op.f('ix_readmission_risks_id'), 'readmission_risks', ['id'], unique=False)
    op.create_index(op.f('ix_readmission_risks_patient_id'), 'readmission_risks', ['patient_id'], unique=False)
    op.create_table('secure_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('urgency_score', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('flagged_keywords', sa.Text(), nullable=True),
    sa.Column('draft_response', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_secure_messages_patient_id_patients')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_secure_messages_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secure_messages'))
    )
    op.create_index(op.f('ix_secure_messages_id'), 'secure_messages', ['id'], unique=False)
    op.create_index(op.f('ix_secure_messages_patient_id'), 'secure_messages', ['patient_id'], unique=False)
    op.create_table('shift_handovers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('generated_by_id', sa.Integer(), nullable=False),
    sa.Column('shift_type', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], name=op.f('fk_shift_handovers_generated_by_id_users')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_shift_handovers_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_handovers'))
    )
    op.create_index(op.f('ix_shift_handovers_id'), 'shift_handovers', ['id'], unique=False)
    op.create_table('patient_communications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('simplified_diagnosis', sa.Text(), nullable=True),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.Column('medication_explanation', sa.Text(), nullable=True),
    sa.Column('warning_signs', sa.Text(), nullable=True),
    sa.Column('next_steps', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['clinical_notes.id'], name=op.f('fk_patient_communications_note_id_clinical_notes')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_patient_communications_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_communications'))
    )
    op.create_index(op.f('ix_patient_communications_id'), 'patient_communications', ['id'], unique=False)
    op.create_index(op.f('ix_patient_communications_patient_id'), 'patient_communications', ['patient_id'], unique=False)
    op.create_table('medication_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], name=op.f('fk_medication_alerts_medication_id_medications')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_medication_alerts_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medication_alerts'))
    )
    op.create_index(op.f('ix_medication_alerts_id'), 'medication_alerts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medication_alerts_id'), table_name='medication_alerts')
    op.drop_table('medication_alerts')
    op.drop_index(op.f('ix_patient_communications_patient_id'), table_name='patient_communications')
    op.drop_index(op.f('ix_patient_communications_id'), table_name='patient_communications')
    op.drop_table('patient_communications')
    op.drop_index(op.f('ix_shift_handovers_id'), table_name='shift_handovers')
    op.drop_table('shift_handovers')
    op.drop_index(op.f('ix_secure_messages_patient_id'), table_name='secure_messages')
    op.drop_index(op.f('ix_secure_messages_id'), table_name='secure_messages')
    op.drop_table('secure_messages')
    op.drop_index(op.f('ix_readmission_risks_patient_id'), table_name='readmission_risks')
    op.drop_index(op.f('ix_readmission_risks_id'), table_name='readmission_risks')
    op.drop_table('readmission_risks')
    # ### end Alembic commands ###
