"""initial migration

Revision ID: 32d7018daa80
Revises: 
Create Date: 2026-01-29 10:47:14.849047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d7018daa80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_billing_items_code'), 'billing_items', ['code'], unique=False)
    op.create_index(op.f('ix_billing_items_status'), 'billing_items', ['status'], unique=False)
    op.create_foreign_key(None, 'medications', 'clinical_notes', ['source_note_id'], ['id'])
    op.create_foreign_key(None, 'procedures', 'clinical_notes', ['source_note_id'], ['id'])
    op.create_foreign_key(None, 'procedures', 'admissions', ['admission_id'], ['id'])
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_constraint(None, 'procedures', type_='foreignkey')
    op.drop_constraint(None, 'procedures', type_='foreignkey')
    op.drop_constraint(None, 'medications', type_='foreignkey')
    op.drop_index(op.f('ix_billing_items_status'), table_name='billing_items')
    op.drop_index(op.f('ix_billing_items_code'), table_name='billing_items')
    # ### end Alembic commands ###
