"""Add patient portal link table

Revision ID: 73379ff6283a
Revises: cdc16ead8e9a
Create Date: 2026-03-25 16:06:39.445026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73379ff6283a'
down_revision: Union[str, Sequence[str], None] = 'cdc16ead8e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_portal_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['ai_encounters.id'], name=op.f('fk_patient_portal_links_encounter_id_ai_encounters')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_patient_portal_links_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_portal_links'))
    )
    op.create_index(op.f('ix_patient_portal_links_encounter_id'), 'patient_portal_links', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_patient_portal_links_id'), 'patient_portal_links', ['id'], unique=False)
    op.create_index(op.f('ix_patient_portal_links_patient_id'), 'patient_portal_links', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_portal_links_token'), 'patient_portal_links', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_portal_links_token'), table_name='patient_portal_links')
    op.drop_index(op.f('ix_patient_portal_links_patient_id'), table_name='patient_portal_links')
    op.drop_index(op.f('ix_patient_portal_links_id'), table_name='patient_portal_links')
    op.drop_index(op.f('ix_patient_portal_links_encounter_id'), table_name='patient_portal_links')
    op.drop_table('patient_portal_links')
    # ### end Alembic commands ###
