"""Workflow Engine Models

Revision ID: 7afc72cbc57c
Revises: c76d78e4c530
Create Date: 2026-02-13 13:10:25.860730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7afc72cbc57c'
down_revision: Union[str, Sequence[str], None] = 'c76d78e4c530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discharge_readiness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('readiness_score', sa.Integer(), nullable=True),
    sa.Column('missing_requirements', sa.Text(), nullable=True),
    sa.Column('suggested_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admission_id'], ['admissions.id'], name=op.f('fk_discharge_readiness_admission_id_admissions')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_discharge_readiness_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discharge_readiness'))
    )
    op.create_index(op.f('ix_discharge_readiness_admission_id'), 'discharge_readiness', ['admission_id'], unique=False)
    op.create_index(op.f('ix_discharge_readiness_id'), 'discharge_readiness', ['id'], unique=False)
    op.create_index(op.f('ix_discharge_readiness_patient_id'), 'discharge_readiness', ['patient_id'], unique=False)
    op.create_table('clinical_trajectories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('trend', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('key_changes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['clinical_notes.id'], name=op.f('fk_clinical_trajectories_note_id_clinical_notes')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_clinical_trajectories_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clinical_trajectories'))
    )
    op.create_index(op.f('ix_clinical_trajectories_id'), 'clinical_trajectories', ['id'], unique=False)
    op.create_index(op.f('ix_clinical_trajectories_note_id'), 'clinical_trajectories', ['note_id'], unique=False)
    op.create_index(op.f('ix_clinical_trajectories_patient_id'), 'clinical_trajectories', ['patient_id'], unique=False)
    op.add_column('clinical_notes', sa.Column('patient_summary', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('source_note_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('category', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('is_auto_generated', sa.Boolean(), nullable=True))
    op.create_foreign_key(op.f('fk_tasks_source_note_id_clinical_notes'), 'tasks', 'clinical_notes', ['source_note_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tasks_source_note_id_clinical_notes'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'is_auto_generated')
    op.drop_column('tasks', 'category')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'source_note_id')
    op.drop_column('clinical_notes', 'patient_summary')
    op.drop_index(op.f('ix_clinical_trajectories_patient_id'), table_name='clinical_trajectories')
    op.drop_index(op.f('ix_clinical_trajectories_note_id'), table_name='clinical_trajectories')
    op.drop_index(op.f('ix_clinical_trajectories_id'), table_name='clinical_trajectories')
    op.drop_table('clinical_trajectories')
    op.drop_index(op.f('ix_discharge_readiness_patient_id'), table_name='discharge_readiness')
    op.drop_index(op.f('ix_discharge_readiness_id'), table_name='discharge_readiness')
    op.drop_index(op.f('ix_discharge_readiness_admission_id'), table_name='discharge_readiness')
    op.drop_table('discharge_readiness')
    # ### end Alembic commands ###
