"""add_news2_score_to_insights

Revision ID: 80e02356b095
Revises: 01f62b44e166
Create Date: 2026-03-25 18:05:20.678704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80e02356b095'
down_revision: Union[str, Sequence[str], None] = '01f62b44e166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_ai_insights', sa.Column('news2_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinical_ai_insights', 'news2_score')
    # ### end Alembic commands ###
