"""Add missing fields to models

Revision ID: 88d436e709f9
Revises: ddbfcdea7996
Create Date: 2026-02-26 12:51:11.345414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d436e709f9'
down_revision: Union[str, Sequence[str], None] = 'ddbfcdea7996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_notes', sa.Column('encounter_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_clinical_notes_encounter_date'), 'clinical_notes', ['encounter_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_notes_encounter_date'), table_name='clinical_notes')
    op.drop_column('clinical_notes', 'encounter_date')
    # ### end Alembic commands ###
