"""Add status and fix condition name

Revision ID: baa103759f94
Revises: 32d7018daa80
Create Date: 2026-01-29 11:53:07.311119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa103759f94'
down_revision: Union[str, Sequence[str], None] = '32d7018daa80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_medications_source_note_id_clinical_notes'), 'clinical_notes', ['source_note_id'], ['id'])

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_status'), ['status'], unique=False)

    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_procedures_source_note_id_clinical_notes'), 'clinical_notes', ['source_note_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_procedures_admission_id_admissions'), 'admissions', ['admission_id'], ['id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_due_date'))

    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_procedures_admission_id_admissions'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_procedures_source_note_id_clinical_notes'), type_='foreignkey')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_status'))
        batch_op.drop_column('status')

    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_medications_source_note_id_clinical_notes'), type_='foreignkey')

    # ### end Alembic commands ###
