"""Make mrn unique per user

Revision ID: c337a59b9ed2
Revises: e7f0f906b7ec
Create Date: 2026-02-09 12:23:04.134775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c337a59b9ed2'
down_revision: Union[str, Sequence[str], None] = 'e7f0f906b7ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=False)
    op.create_unique_constraint('uq_patient_user_mrn', 'patients', ['user_id', 'mrn'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_patient_user_mrn', 'patients', type_='unique')
    op.drop_index(op.f('ix_patients_mrn'), table_name='patients')
    op.create_index(op.f('ix_patients_mrn'), 'patients', ['mrn'], unique=True)
    # ### end Alembic commands ###
