"""Add cached summary to patient

Revision ID: c389b13b129c
Revises: c337a59b9ed2
Create Date: 2026-02-09 15:37:38.886411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c389b13b129c'
down_revision: Union[str, Sequence[str], None] = 'c337a59b9ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('cached_summary', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('summary_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'summary_updated_at')
    op.drop_column('patients', 'cached_summary')
    # ### end Alembic commands ###
