"""Fix Rel and Add HOS Tables

Revision ID: c76d78e4c530
Revises: 022f91de23d4
Create Date: 2026-02-13 12:45:30.369729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c76d78e4c530'
down_revision: Union[str, Sequence[str], None] = '022f91de23d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_ai_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workload_score', sa.Float(), nullable=True),
    sa.Column('burnout_probability', sa.Float(), nullable=True),
    sa.Column('active_patients_count', sa.Integer(), nullable=True),
    sa.Column('notes_last_7d', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_doctor_ai_metrics_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctor_ai_metrics'))
    )
    op.create_index(op.f('ix_doctor_ai_metrics_id'), 'doctor_ai_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_ai_metrics_user_id'), 'doctor_ai_metrics', ['user_id'], unique=True)
    op.create_table('hospital_patient_risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('suggested_actions', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_hospital_patient_risk_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hospital_patient_risk'))
    )
    op.create_index(op.f('ix_hospital_patient_risk_id'), 'hospital_patient_risk', ['id'], unique=False)
    op.create_index(op.f('ix_hospital_patient_risk_patient_id'), 'hospital_patient_risk', ['patient_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hospital_patient_risk_patient_id'), table_name='hospital_patient_risk')
    op.drop_index(op.f('ix_hospital_patient_risk_id'), table_name='hospital_patient_risk')
    op.drop_table('hospital_patient_risk')
    op.drop_index(op.f('ix_doctor_ai_metrics_user_id'), table_name='doctor_ai_metrics')
    op.drop_index(op.f('ix_doctor_ai_metrics_id'), table_name='doctor_ai_metrics')
    op.drop_table('doctor_ai_metrics')
    # ### end Alembic commands ###
