"""add_clinical_intelligence_ai_encounter_tables

Revision ID: ddbfcdea7996
Revises: 0c4b24e55b7f
Create Date: 2026-02-25 10:57:01.374421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddbfcdea7996'
down_revision: Union[str, Sequence[str], None] = '0c4b24e55b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_encounters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('encounter_date', sa.DateTime(), nullable=False),
    sa.Column('raw_note', sa.Text(), nullable=False),
    sa.Column('soap_note', sa.Text(), nullable=True),
    sa.Column('chief_complaint', sa.String(), nullable=True),
    sa.Column('case_status', sa.String(), nullable=True),
    sa.Column('billing_complexity', sa.String(), nullable=True),
    sa.Column('admission_required', sa.Boolean(), nullable=True),
    sa.Column('icu_required', sa.Boolean(), nullable=True),
    sa.Column('follow_up_days', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.String(), nullable=True),
    sa.Column('risk_flags', sa.Text(), nullable=True),
    sa.Column('legal_flags', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('token_usage', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], name=op.f('fk_ai_encounters_confirmed_by_id_users')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_ai_encounters_created_by_id_users')),
    sa.ForeignKeyConstraint(['note_id'], ['clinical_notes.id'], name=op.f('fk_ai_encounters_note_id_clinical_notes')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_ai_encounters_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_encounters'))
    )
    op.create_index(op.f('ix_ai_encounters_created_at'), 'ai_encounters', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_encounters_id'), 'ai_encounters', ['id'], unique=False)
    op.create_index(op.f('ix_ai_encounters_note_id'), 'ai_encounters', ['note_id'], unique=False)
    op.create_index(op.f('ix_ai_encounters_patient_id'), 'ai_encounters', ['patient_id'], unique=False)
    op.create_table('ai_followup_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('follow_up_type', sa.String(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('suggested_days', sa.Integer(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('converted_task_id', sa.Integer(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['converted_task_id'], ['tasks.id'], name=op.f('fk_ai_followup_recommendations_converted_task_id_tasks')),
    sa.ForeignKeyConstraint(['encounter_id'], ['ai_encounters.id'], name=op.f('fk_ai_followup_recommendations_encounter_id_ai_encounters')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_ai_followup_recommendations_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_followup_recommendations'))
    )
    op.create_index(op.f('ix_ai_followup_recommendations_encounter_id'), 'ai_followup_recommendations', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_ai_followup_recommendations_id'), 'ai_followup_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_ai_followup_recommendations_patient_id'), 'ai_followup_recommendations', ['patient_id'], unique=False)
    op.create_table('ai_generated_billing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('cpt_code', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('complexity', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=True),
    sa.Column('review_reason', sa.String(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmed_billing_id', sa.Integer(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_billing_id'], ['billing_items.id'], name=op.f('fk_ai_generated_billing_confirmed_billing_id_billing_items')),
    sa.ForeignKeyConstraint(['encounter_id'], ['ai_encounters.id'], name=op.f('fk_ai_generated_billing_encounter_id_ai_encounters')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_ai_generated_billing_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_generated_billing'))
    )
    op.create_index(op.f('ix_ai_generated_billing_encounter_id'), 'ai_generated_billing', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_ai_generated_billing_id'), 'ai_generated_billing', ['id'], unique=False)
    op.create_index(op.f('ix_ai_generated_billing_patient_id'), 'ai_generated_billing', ['patient_id'], unique=False)
    op.create_table('ai_generated_diagnoses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('condition_name', sa.String(), nullable=False),
    sa.Column('icd10_code', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['ai_encounters.id'], name=op.f('fk_ai_generated_diagnoses_encounter_id_ai_encounters')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_ai_generated_diagnoses_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_generated_diagnoses'))
    )
    op.create_index(op.f('ix_ai_generated_diagnoses_encounter_id'), 'ai_generated_diagnoses', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_ai_generated_diagnoses_id'), 'ai_generated_diagnoses', ['id'], unique=False)
    op.create_index(op.f('ix_ai_generated_diagnoses_patient_id'), 'ai_generated_diagnoses', ['patient_id'], unique=False)
    op.create_table('ai_generated_medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('dosage', sa.String(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('route', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('start_date_text', sa.String(), nullable=True),
    sa.Column('requires_confirmation', sa.Boolean(), nullable=True),
    sa.Column('fields_required', sa.Text(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('confirmed_medication_id', sa.Integer(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_medication_id'], ['medications.id'], name=op.f('fk_ai_generated_medications_confirmed_medication_id_medications')),
    sa.ForeignKeyConstraint(['encounter_id'], ['ai_encounters.id'], name=op.f('fk_ai_generated_medications_encounter_id_ai_encounters')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_ai_generated_medications_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_generated_medications'))
    )
    op.create_index(op.f('ix_ai_generated_medications_encounter_id'), 'ai_generated_medications', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_ai_generated_medications_id'), 'ai_generated_medications', ['id'], unique=False)
    op.create_index(op.f('ix_ai_generated_medications_patient_id'), 'ai_generated_medications', ['patient_id'], unique=False)
    op.create_table('ai_timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encounter_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=False),
    sa.Column('event_date_text', sa.String(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['encounter_id'], ['ai_encounters.id'], name=op.f('fk_ai_timeline_events_encounter_id_ai_encounters')),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_ai_timeline_events_patient_id_patients')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_timeline_events'))
    )
    op.create_index(op.f('ix_ai_timeline_events_encounter_id'), 'ai_timeline_events', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_ai_timeline_events_id'), 'ai_timeline_events', ['id'], unique=False)
    op.create_index(op.f('ix_ai_timeline_events_patient_id'), 'ai_timeline_events', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_timeline_events_patient_id'), table_name='ai_timeline_events')
    op.drop_index(op.f('ix_ai_timeline_events_id'), table_name='ai_timeline_events')
    op.drop_index(op.f('ix_ai_timeline_events_encounter_id'), table_name='ai_timeline_events')
    op.drop_table('ai_timeline_events')
    op.drop_index(op.f('ix_ai_generated_medications_patient_id'), table_name='ai_generated_medications')
    op.drop_index(op.f('ix_ai_generated_medications_id'), table_name='ai_generated_medications')
    op.drop_index(op.f('ix_ai_generated_medications_encounter_id'), table_name='ai_generated_medications')
    op.drop_table('ai_generated_medications')
    op.drop_index(op.f('ix_ai_generated_diagnoses_patient_id'), table_name='ai_generated_diagnoses')
    op.drop_index(op.f('ix_ai_generated_diagnoses_id'), table_name='ai_generated_diagnoses')
    op.drop_index(op.f('ix_ai_generated_diagnoses_encounter_id'), table_name='ai_generated_diagnoses')
    op.drop_table('ai_generated_diagnoses')
    op.drop_index(op.f('ix_ai_generated_billing_patient_id'), table_name='ai_generated_billing')
    op.drop_index(op.f('ix_ai_generated_billing_id'), table_name='ai_generated_billing')
    op.drop_index(op.f('ix_ai_generated_billing_encounter_id'), table_name='ai_generated_billing')
    op.drop_table('ai_generated_billing')
    op.drop_index(op.f('ix_ai_followup_recommendations_patient_id'), table_name='ai_followup_recommendations')
    op.drop_index(op.f('ix_ai_followup_recommendations_id'), table_name='ai_followup_recommendations')
    op.drop_index(op.f('ix_ai_followup_recommendations_encounter_id'), table_name='ai_followup_recommendations')
    op.drop_table('ai_followup_recommendations')
    op.drop_index(op.f('ix_ai_encounters_patient_id'), table_name='ai_encounters')
    op.drop_index(op.f('ix_ai_encounters_note_id'), table_name='ai_encounters')
    op.drop_index(op.f('ix_ai_encounters_id'), table_name='ai_encounters')
    op.drop_index(op.f('ix_ai_encounters_created_at'), table_name='ai_encounters')
    op.drop_table('ai_encounters')
    # ### end Alembic commands ###
