"""Add user_id to patients

Revision ID: e7f0f906b7ec
Revises: ace12bfa1627
Create Date: 2026-02-09 12:17:38.894096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f0f906b7ec'
down_revision: Union[str, Sequence[str], None] = 'ace12bfa1627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_patients_user_id'), 'patients', ['user_id'], unique=False)
    op.create_foreign_key(op.f('fk_patients_user_id_users'), 'patients', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_patients_user_id_users'), 'patients', type_='foreignkey')
    op.drop_index(op.f('ix_patients_user_id'), table_name='patients')
    op.drop_column('patients', 'user_id')
    # ### end Alembic commands ###
